-- Create categories table
CREATE TABLE categories (
  id TEXT PRIMARY KEY,
  label TEXT NOT NULL
);

-- Insert default categories
INSERT INTO categories (id, label) VALUES
  ('it_gadget', 'โทรศัพท์ / ไอที'),
  ('personal', 'ของใช้ส่วนตัว'),
  ('stationery', 'หนังสือ / เครื่องเขียน'),
  ('other', 'อื่นๆ');

-- Create items table
CREATE TABLE items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT NOT NULL,
  category TEXT REFERENCES categories(id),
  location TEXT,
  date BIGINT,
  description TEXT,
  image TEXT,
  status BOOLEAN DEFAULT true, -- true = found, false = returned
  contact TEXT,
  claimer_name TEXT,
  claimer_phone TEXT
);

-- Enable Row Level Security (RLS)
ALTER TABLE items ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

-- Create policies (Adjust as needed for your security model)
-- Allow public read access to categories
CREATE POLICY "Public categories are viewable by everyone" ON categories
  FOR SELECT USING (true);

-- Allow public read access to items
CREATE POLICY "Public items are viewable by everyone" ON items
  FOR SELECT USING (true);

-- Allow authenticated users (admin) to insert/update/delete items
CREATE POLICY "Authenticated users can modify items" ON items
  FOR ALL USING (auth.role() = 'authenticated');

-- Storage Bucket Policy (Run this in SQL Editor if needed, or configure via UI)
INSERT INTO storage.buckets (id, name, public) VALUES ('item-images', 'item-images', true);
CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING ( bucket_id = 'item-images' );
CREATE POLICY "Authenticated Upload" ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'item-images' AND auth.role() = 'authenticated' );
