-- ==========================================
-- 1. Tables
-- ==========================================

-- Create categories table
CREATE TABLE IF NOT EXISTS categories (
  id TEXT PRIMARY KEY,
  label TEXT NOT NULL
);

-- Insert default categories (ignore if they exist)
INSERT INTO categories (id, label) VALUES
  ('it_gadget', 'โทรศัพท์ / ไอที'),
  ('personal', 'ของใช้ส่วนตัว'),
  ('stationery', 'หนังสือ / เครื่องเขียน'),
  ('other', 'อื่นๆ')
ON CONFLICT (id) DO NOTHING;

-- Create items table
CREATE TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT NOT NULL,
  category TEXT REFERENCES categories(id),
  location TEXT,
  date BIGINT,
  description TEXT,
  image TEXT,
  status BOOLEAN DEFAULT true, -- true = found, false = returned
  contact TEXT,
  claimer_name TEXT,
  claimer_phone TEXT
);

-- ==========================================
-- 2. Row Level Security (RLS) for Tables
-- ==========================================

-- Enable RLS
ALTER TABLE items ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

-- Categories Policies
CREATE POLICY "Public categories are viewable by everyone" ON categories
  FOR SELECT USING (true);

-- Items Policies
CREATE POLICY "Public items are viewable by everyone" ON items
  FOR SELECT USING (true);

CREATE POLICY "Authenticated users can insert items" ON items
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can update items" ON items
  FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can delete items" ON items
  FOR DELETE USING (auth.role() = 'authenticated');

-- ==========================================
-- 3. Storage
-- ==========================================

-- Create the storage bucket 'item-images' if it doesn't exist
INSERT INTO storage.buckets (id, name, public)
VALUES ('item-images', 'item-images', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies
-- Allow public read access to all files in the bucket
CREATE POLICY "Public Access to item-images" ON storage.objects
  FOR SELECT USING ( bucket_id = 'item-images' );

-- Allow authenticated users to upload files
CREATE POLICY "Authenticated users can upload images" ON storage.objects
  FOR INSERT WITH CHECK (
    bucket_id = 'item-images' AND
    auth.role() = 'authenticated'
);

-- Allow authenticated users to update their uploaded files
CREATE POLICY "Authenticated users can update images" ON storage.objects
  FOR UPDATE USING (
    bucket_id = 'item-images' AND
    auth.role() = 'authenticated'
);

-- Allow authenticated users to delete files
CREATE POLICY "Authenticated users can delete images" ON storage.objects
  FOR DELETE USING (
    bucket_id = 'item-images' AND
    auth.role() = 'authenticated'
);
